version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
     - "443:443"
     - "80:80"
    restart: always
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ramhouch/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ramhouch/data/wordpress
networks:
  inception: