version: "3.5"

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
     - "443:443"
    restart: always
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/.
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp/.
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
  websites:
    container_name: websites
    image: websites
    build: ./requirements/bonus/websites/.
    ports:
      - "3000:3000"
    restart: always
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build: ./requirements/bonus/cadvisor/.
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: always
  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer/.
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis/.
    env_file:
      - .env
    restart: always
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ramhouch/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ramhouch/data/wordpress
networks:
  inception: