version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./services/nginx/.
    ports:
     - "443:443"
     - "80:80"
    restart: always
  mariadb:
    container_name: mariadb
    build: ./services/mariadb/.
    restart: always
    env_file:
      - .env

